# Generated by Django 4.1.7 on 2023-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpopstore', '0004_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
