# Generated by Django 4.1.7 on 2023-05-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_user_image_user_phone_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
