# Generated by Django 4.1.7 on 2023-04-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpopstore', '0006_remove_order_ordered_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placed_at',
            new_name='date_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpopstore.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
